# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 768b36e24b308a54df3aa7091cf5787708ec3393d643d0c61025624289f2badb410ca1b9ad7aaf2ecca63468122843368b0d3c4be157fd0172828fbc810329c0

test:
  secret_key_base: 41c62cd50e3d902dd575e66400edc3b8af27d5666b956b89d4fe6111c4d21628dd8934f6d6f43fcc2c0888a06f8218eb865aada8a7bc48c561d3d12558243f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
